Help documentation updates
tidymodels/rsample pull request #182
Opened 2020-09-11 05:56 UTC by irkaal

Fixes typo in doc

2020-09-11 12:08 UTC, DavisVaughan requested changes
This looks great! We really appreciate these kinds of PRs. I have one comment below, but otherwise this is awesome, thanks!

2020-09-11 12:08 UTC, DavisVaughan commented on R/slide.R
> +#'   which is relevant when every value is `> 1`.
This one was actually almost correct before, but it should have been

```
when the `every` value
```

`every` is a function argument, which is what i was talking about here. Can you please update this to what I showed above?

2020-09-11 16:17 UTC, irkaal commented on R/slide.R
> +#'   which is relevant when every value is `> 1`.
Yes, of course. Sorry about that!

2020-09-14 12:19 UTC, merged

2020-09-14 12:19 UTC, DavisVaughan commented
Thank you!