Added permutation resampling functions
tidymodels/rsample pull request #200
Opened 2020-10-23 21:16 UTC by mattwarkentin

Closes #198

2020-10-23 21:33 UTC, mattwarkentin commented
GitHub Action failures are the same as #199. Unrelated to my PR.

2020-10-26 23:40 UTC, topepo requested changes
Can you update the NEWS and `_pkgdown.yml` files too?

2020-10-26 23:40 UTC, topepo commented on R/permutations.R
> +    stop("You must specify at least one column to permute!")
Please use `rlang::abort()`

2020-10-26 23:40 UTC, topepo commented on R/rsplit.R
> +  if (!is.null(x$col_id)) {
Can you change the message to use the class of `x` instead of hard-coding it?

2020-10-26 23:40 UTC, topepo commented on R/permutations.R
> +#'   t.test(hp ~ vs, data = analysis(x))$p.value
I would return the estimate instead of the p-value.

2020-10-26 23:40 UTC, topepo commented on R/permutations.R
> +#'   t.test(hp ~ vs, data = analysis(x))$p.value
Actually, the `statistic` field.

2020-10-26 23:40 UTC, topepo commented on R/permutations.R
> +#' @param permute <`tidy-select`> One or more unquoted
I'm not a fan of this documentation style. Can you remove "<`tidy-select`>"?

2020-10-27 01:02 UTC, mattwarkentin commented on R/permutations.R
> +#' @param permute <`tidy-select`> One or more unquoted
Sure, no problem. I was trying to be consistent with how `dplyr` and `tidyr` often describe accepting `tidyselect` selectors. But happy to change.

2020-10-27 15:00 UTC, mattwarkentin commented
Completed all suggested revision, @topepo. I also added the `col_id` as an attribute to the `tibble` as a whole. I think it makes it easy for users to double-check which columns which columns were shuffled. I also think that if `rsample` print messages ever get a makeover with `cli`, then this attribute would be useful for printing more informative messages.

Please let me know if you would like this reverted.

2020-10-27 23:07 UTC, topepo commented
That's a good idea. Can you add some tests? We should make sure that: 

 * filtering rows reverts the class to tibble and
 * column binding a data set keeps the default classes.

2020-10-28 18:47 UTC, mattwarkentin commented
Hey Max,

I added tests for class inheritance for filtering and slicing rows, and also different ways of column binding involving a permutation `rset` object. I also went ahead and made the update to the `print` method as shown below. More so than with other resample methods, I think its really important to know details about how the permutation was performed (i.e which columns were shuffled), so I thought making it more obvious with the `print` method was important. Let me know what you think! 

``` r
library(rsample)
permutations(mtcars, 1:3)
#> # Permutation sampling 
#> # Permuted columns: [mpg, cyl, disp] 
#> # A tibble: 25 x 2
#>    splits         id            
#>    <list>         <chr>         
#>  1 <split [32/0]> Permutations01
#>  2 <split [32/0]> Permutations02
#>  3 <split [32/0]> Permutations03
#>  4 <split [32/0]> Permutations04
#>  5 <split [32/0]> Permutations05
#>  6 <split [32/0]> Permutations06
#>  7 <split [32/0]> Permutations07
#>  8 <split [32/0]> Permutations08
#>  9 <split [32/0]> Permutations09
#> 10 <split [32/0]> Permutations10
#> # … with 15 more rows
```

2020-10-30 20:06 UTC, topepo commented
I think that it's a good idea.

2020-10-30 20:09 UTC, topepo commented
I think that an update to the `_pkgdown.yml` file is all that is left.

2020-10-30 20:20 UTC, mattwarkentin commented
Already done in 2423137 [(see here)](https://github.com/tidymodels/rsample/commit/24231371cbdaa8558d8ee5dd7d88c8530bee7a31#diff-f5f791eb2285a738ec729c44088e49a60ddf355eb479fb1fb5df7fcea4fea2e8)

2020-10-30 20:21 UTC, merged