Add id to initial_time_split()
tidymodels/rsample pull request #205
Opened 2020-11-30 21:01 UTC by juliasilge

Closes #175 

``` r
library(rsample)

split1 <- initial_split(mtcars)
split1$id
#> # A tibble: 1 x 1
#>   id       
#>   <chr>    
#> 1 Resample1

split2 <- initial_time_split(mtcars)
split2$id
#> # A tibble: 1 x 1
#>   id       
#>   <chr>    
#> 1 Resample1
```

<sup>Created on 2020-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I don't know if we want to make this change as shown here with `manual_rset()`, or just by adding the `id` in by assignment. Thoughts?

(By the way, the problem with `last_fit()` as shown in the linked issue is no longer a problem as of the new tune release, even without the `id`.)

2020-11-30 23:06 UTC, juliasilge commented
Chatting with Max today, we both said we lean toward using the "constructor"-ish `manual_rset()`, although it is sort of A LOT.

2020-12-01 13:24 UTC, DavisVaughan requested changes

2020-12-01 13:24 UTC, DavisVaughan commented on R/initial_split.R
> +  res <- manual_rset(
The reason this even works is that `manual_rset()` eventually calls `new_rset()`, and `new_rset()` is what adds the id bits to the splits. So really all you need here is `new_rset()`. You can probably do something like:

```r
split <- rsplit(data, 1:n_train, (n_train + 1 - lag):nrow(data))
splits <- list(split)
ids <- "Resample1"
rset <- new_rset(splits, ids)
rset$splits[[1]]
```

That would be fine for now, but I'm pretty convinced that we shouldn't be adding the id in `new_rset()`, it should be done in `rsplit()`. Then it would just be:

```r
rsplit(data, 1:n_train, (n_train + 1 - lag):nrow(data), id = "Resample1")
```

Something to think about at another time I guess

2020-12-01 16:05 UTC, juliasilge commented on R/initial_split.R
> +  res <- manual_rset(
Thank you! 👍

2020-12-01 16:10 UTC, merged