PR related to issue #217.
tidymodels/rsample pull request #219
Opened 2021-02-16 23:50 UTC by issactoast

Hi @juliasilge 

This PR related to issue #217 

I have been thinking about this since I found `strat_sample` sounds good to me, so I fork the package and let my data flow the functions. 

I found two parts is switched which make the result different than `sample_frac` in `dplyr`

I twicked `mc_splits` input from 1-prop to prop, so that the functions in mc.R find the index for prop. And I finally use `ind` for the analysis. 

These two chance makes the result from rsample and dplyr to be the same as follows;

``` r
#sample_frac and sample_n
library(dplyr)

set.seed(2021)
dim(airquality)
#> [1] 153   6

#sample 10% from each month
airquality_frac <- airquality %>% 
  group_by(Month) %>%  
  sample_frac(size = 0.1, replace=FALSE)

library(rsample)

airquality_split <- initial_split(airquality, prop = 0.1,
                                  strata = "Month")

airquality_frac2 <- training(airquality_split)

dim(airquality_frac)
#> [1] 15  6
dim(airquality_frac2)
#> [1] 15  6
```

Could you give me a feedback? I have feeling that this resolves the issue (user expectation about prop input) and increases the coherence between the tidymodels and the tidyverse packages. What do you think?

2021-02-17 16:28 UTC, issactoast commented
I resolved the testthat package issue and the prop change in validation_split.R

2021-02-19 15:59 UTC, DavisVaughan requested changes
Thanks @issactoast! This looks like the right thing to do (as noted in https://github.com/tidymodels/rsample/issues/217#issuecomment-782151875). I have a few comments. Once you make these changes, I'll merge.

Notes to self:
- Rebase on master before merging
- Add a NEWS bullet (wait until after rebasing to keep this news entry separate from the 0.0.9 ones)

2021-02-19 15:59 UTC, DavisVaughan commented on R/mc.R
> +              prop = prop, # prop for train set
Could you please remove the comment? We can always look back at this PR and the associated issue if we are wondering why the code is written this way

2021-02-19 15:59 UTC, DavisVaughan commented on R/mc.R
> +  list(analysis = ind, # ind for analysis
Same, no comment needed

2021-02-19 15:59 UTC, DavisVaughan commented on R/mc.R
>  # Get the indices of the analysis set from the assessment set
Could you please update this comment to say:

```
# Get the indices of the assessment set from the analysis set
```

2021-02-19 15:59 UTC, DavisVaughan commented on R/validation_split.R
> +              prop = prop, # prop for analysis
Same, no comment required

2021-02-19 15:59 UTC, DavisVaughan commented on tests/testthat/test_validation.R
> +  expect_true(all(sizes3$assessment == 15))
Could you please also the following test to `test_initial.R`:

```r
test_that("`prop` computes the proportion for analysis (#217)", {
  set.seed(11)
  
  props <- c(.1, .9)
  
  for (prop in props) {
    # Not stratified
    split <- initial_split(airquality, prop = prop)
    actual <- nrow(analysis(split))
    expect <- as.integer(floor(nrow(airquality) * prop))
    
    expect_identical(actual, expect)
    
    # Stratified
    split <- initial_split(airquality, prop = prop, strata = Month)
    actual <- nrow(analysis(split))
    expect <- as.integer(sum(floor(table(airquality$Month) * prop)) )
    
    expect_identical(actual, expect)
  }
})
```

This should ensure that this can't happen again. Adding a test like this is also a more robust alternative for the comments you had added directly in the code (which I requested you remove)

2021-02-19 17:32 UTC, issactoast commented
I have 
- removed and updated the comments on mc.R and  validation_split.R.
- added testthat code to the test_initial.R

Wow, this PR is my first contribution to the R community! It feels awesome! Thank you @DavisVaughan and @juliasilge! :)

2021-02-19 19:06 UTC, DavisVaughan commented
Perfect, I'll take it from here!

2021-02-19 19:15 UTC, merged

2021-02-19 19:16 UTC, DavisVaughan commented
Thanks @issactoast! That was a very useful first contribution!

2021-02-19 22:16 UTC, issactoast commented
@DavisVaughan Wonderful! Thank you for the concrete comment! 👍